// Generated by tools/generate_duchess_cards.py. Edit design/duchess/cards.json.
using System.Collections.Generic;
using MegaCrit.Sts2.Core.Entities.Cards;
namespace NightMustStay.Core.Models.Cards;
public static class DuchessCardCatalog { public static readonly Dictionary<string, DuchessCardSpec> All = new() {
["DuchessStrike"] = new(1, CardType.Attack, CardRarity.Basic, new DuchessEffect[] { new("Damage", 6m, 9m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessDefend"] = new(1, CardType.Skill, CardRarity.Basic, new DuchessEffect[] { new("Block", 5m, 8m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessRestage"] = new(0, CardType.Attack, CardRarity.Basic, new DuchessEffect[] { new("Damage", 4m, 6m, "") }, Hits: 1, All: false, Exhaust: false, Retain: true, UpgradeTokens: false, Reaction: false, Moment: 5, RestageDivisor: 3),
["DuchessElegantBearing"] = new(1, CardType.Skill, CardRarity.Basic, new DuchessEffect[] { new("DodgeToDraw", 3m, 3m, ""), new("Draw", 2m, 2m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: true, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessStiletto"] = new(1, CardType.Attack, CardRarity.Common, new DuchessEffect[] { new("Damage", 6m, 9m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: true, Moment: 0, RestageDivisor: 0),
["DuchessTwinFangs"] = new(1, CardType.Attack, CardRarity.Common, new DuchessEffect[] { new("Damage", 4m, 5m, "") }, Hits: 2, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessPassingCut"] = new(1, CardType.Attack, CardRarity.Common, new DuchessEffect[] { new("Damage", 7m, 10m, ""), new("Block", 3m, 4m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: true, Moment: 0, RestageDivisor: 0),
["DuchessLowSweep"] = new(1, CardType.Attack, CardRarity.Common, new DuchessEffect[] { new("Damage", 6m, 8m, "") }, Hits: 1, All: true, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessNeedlework"] = new(1, CardType.Attack, CardRarity.Common, new DuchessEffect[] { new("Damage", 7m, 10m, ""), new("Weak", 1m, 1m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessOpeningThrust"] = new(1, CardType.Attack, CardRarity.Common, new DuchessEffect[] { new("Damage", 9m, 12m, ""), new("Draw", 1m, 1m, "first") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessFollowThrough"] = new(1, CardType.Attack, CardRarity.Common, new DuchessEffect[] { new("Damage", 8m, 11m, ""), new("Draw", 1m, 1m, "afterSkill") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessBlindSpot"] = new(1, CardType.Attack, CardRarity.Common, new DuchessEffect[] { new("Damage", 9m, 12m, ""), new("Vulnerable", 1m, 2m, "moment") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 4, RestageDivisor: 0),
["DuchessSerratedEdge"] = new(2, CardType.Attack, CardRarity.Common, new DuchessEffect[] { new("Damage", 16m, 21m, ""), new("Vulnerable", 1m, 1m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessGlintstoneKnife"] = new(1, CardType.Attack, CardRarity.Common, new DuchessEffect[] { new("Damage", 7m, 9m, ""), new("DodgeToDraw", 1m, 1m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessPartingCut"] = new(1, CardType.Attack, CardRarity.Common, new DuchessEffect[] { new("Damage", 10m, 13m, ""), new("Block", 4m, 4m, "afterAttack") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessMeasuredStep"] = new(1, CardType.Skill, CardRarity.Common, new DuchessEffect[] { new("Block", 8m, 11m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessSilkenGuard"] = new(1, CardType.Skill, CardRarity.Common, new DuchessEffect[] { new("Block", 6m, 8m, ""), new("Draw", 1m, 1m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessPivot"] = new(0, CardType.Skill, CardRarity.Common, new DuchessEffect[] { new("Block", 3m, 5m, ""), new("AdvanceMoment", 1m, 1m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessVeiledStep"] = new(1, CardType.Skill, CardRarity.Common, new DuchessEffect[] { new("DodgeToDraw", 1m, 2m, ""), new("Draw", 1m, 1m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessFeint"] = new(0, CardType.Skill, CardRarity.Common, new DuchessEffect[] { new("AdvanceMoment", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessReadTheRoom"] = new(1, CardType.Skill, CardRarity.Common, new DuchessEffect[] { new("Draw", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessTakeABreath"] = new(0, CardType.Skill, CardRarity.Common, new DuchessEffect[] { new("Energy", 1m, 1m, ""), new("Draw", 1m, 2m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessHiddenPocket"] = new(1, CardType.Skill, CardRarity.Common, new DuchessEffect[] { new("DodgeToDraw", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessSoftLanding"] = new(1, CardType.Skill, CardRarity.Common, new DuchessEffect[] { new("Block", 7m, 10m, ""), new("DodgeToDraw", 1m, 1m, "moment") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 4, RestageDivisor: 0),
["DuchessReverberation"] = new(1, CardType.Skill, CardRarity.Common, new DuchessEffect[] { new("ShuffleDiscard", 1m, 2m, ""), new("Draw", 1m, 2m, ""), new("Block", 4m, 6m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessPoised"] = new(1, CardType.Skill, CardRarity.Common, new DuchessEffect[] { new("Block", 5m, 8m, ""), new("SetMoment", 3m, 3m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessCurtainTug"] = new(1, CardType.Skill, CardRarity.Common, new DuchessEffect[] { new("Weak", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessDistraction"] = new(1, CardType.Skill, CardRarity.Common, new DuchessEffect[] { new("Weak", 1m, 2m, ""), new("Block", 5m, 7m, "") }, Hits: 1, All: true, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessTripleWaltz"] = new(1, CardType.Attack, CardRarity.Uncommon, new DuchessEffect[] { new("Damage", 3m, 4m, "") }, Hits: 3, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessDaggerFan"] = new(1, CardType.Attack, CardRarity.Uncommon, new DuchessEffect[] { new("Damage", 4m, 5m, "") }, Hits: 2, All: true, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessPerfectAngle"] = new(2, CardType.Attack, CardRarity.Uncommon, new DuchessEffect[] { new("Damage", 19m, 25m, ""), new("Vulnerable", 2m, 3m, "moment") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 6, RestageDivisor: 0),
["DuchessMaskedAssault"] = new(1, CardType.Attack, CardRarity.Uncommon, new DuchessEffect[] { new("Damage", 11m, 15m, ""), new("Draw", 1m, 2m, "moment") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: true, Moment: 5, RestageDivisor: 0),
["DuchessDancePartner"] = new(1, CardType.Attack, CardRarity.Uncommon, new DuchessEffect[] { new("Damage", 8m, 11m, ""), new("Vulnerable", 2m, 2m, "afterSkill") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessCutAndFade"] = new(2, CardType.Attack, CardRarity.Uncommon, new DuchessEffect[] { new("Damage", 13m, 17m, ""), new("DodgeToDraw", 1m, 2m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessPaleMoonblade"] = new(2, CardType.Attack, CardRarity.Uncommon, new DuchessEffect[] { new("Damage", 12m, 16m, "") }, Hits: 1, All: true, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessNoWitness"] = new(1, CardType.Attack, CardRarity.Uncommon, new DuchessEffect[] { new("Damage", 12m, 16m, "") }, Hits: 1, All: false, Exhaust: true, Retain: true, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessSecondThought"] = new(1, CardType.Attack, CardRarity.Uncommon, new DuchessEffect[] { new("Damage", 8m, 11m, ""), new("Draw", 1m, 1m, "moment") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: true, Moment: 3, RestageDivisor: 0),
["DuchessThreadTheGap"] = new(1, CardType.Attack, CardRarity.Uncommon, new DuchessEffect[] { new("Damage", 9m, 12m, ""), new("Energy", 1m, 1m, "afterSkill") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessSilverFlash"] = new(2, CardType.Attack, CardRarity.Uncommon, new DuchessEffect[] { new("Damage", 12m, 16m, ""), new("DodgeToDraw", 2m, 2m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: true, Moment: 0, RestageDivisor: 0),
["DuchessUnderstudy"] = new(1, CardType.Skill, CardRarity.Uncommon, new DuchessEffect[] { new("DodgeToHand", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessEncore"] = new(1, CardType.Skill, CardRarity.Uncommon, new DuchessEffect[] { new("ShuffleDiscard", 2m, 3m, ""), new("Draw", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessHeldBreath"] = new(1, CardType.Skill, CardRarity.Uncommon, new DuchessEffect[] { new("DodgeToHand", 1m, 2m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: true, Moment: 0, RestageDivisor: 0),
["DuchessInvitation"] = new(1, CardType.Skill, CardRarity.Uncommon, new DuchessEffect[] { new("AdvanceMoment", 2m, 3m, ""), new("Draw", 1m, 1m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessTurnAside"] = new(1, CardType.Skill, CardRarity.Uncommon, new DuchessEffect[] { new("Block", 9m, 12m, ""), new("DodgeToDraw", 1m, 2m, "moment") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 4, RestageDivisor: 0),
["DuchessBackstage"] = new(1, CardType.Skill, CardRarity.Uncommon, new DuchessEffect[] { new("Draw", 3m, 4m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessQuietSignal"] = new(1, CardType.Skill, CardRarity.Uncommon, new DuchessEffect[] { new("AllyBlock", 6m, 9m, ""), new("AdvanceMoment", 1m, 2m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessMoonlitVeil"] = new(2, CardType.Skill, CardRarity.Uncommon, new DuchessEffect[] { new("AllyDodge", 1m, 2m, ""), new("Block", 7m, 11m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessDressRehearsal"] = new(1, CardType.Skill, CardRarity.Uncommon, new DuchessEffect[] { new("ShuffleHand", 1m, 2m, ""), new("Draw", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessQuickHands"] = new(0, CardType.Skill, CardRarity.Uncommon, new DuchessEffect[] { new("DodgeToHand", 1m, 2m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessStolenMoment"] = new(1, CardType.Skill, CardRarity.Uncommon, new DuchessEffect[] { new("Block", 10m, 14m, ""), new("SetMoment", 3m, 3m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessSway"] = new(1, CardType.Skill, CardRarity.Uncommon, new DuchessEffect[] { new("DodgeToDraw", 1m, 2m, ""), new("AdvanceMoment", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessElegance"] = new(1, CardType.Power, CardRarity.Uncommon, new DuchessEffect[] { new("DodgeAtTurnStart", 1m, 2m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessComposure"] = new(1, CardType.Power, CardRarity.Uncommon, new DuchessEffect[] { new("ReactionBlock", 3m, 4m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessAfterglow"] = new(1, CardType.Power, CardRarity.Uncommon, new DuchessEffect[] { new("MomentFiveBlock", 5m, 8m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessHiddenRhythm"] = new(1, CardType.Power, CardRarity.Uncommon, new DuchessEffect[] { new("MomentFiveDraw", 1m, 2m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessUnseenResolve"] = new(1, CardType.Power, CardRarity.Uncommon, new DuchessEffect[] { new("DodgeMoment", 1m, 2m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessFinale"] = new(2, CardType.Skill, CardRarity.Rare, new DuchessEffect[] { new("AllyDodge", 2m, 3m, ""), new("Draw", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessGrandReprise"] = new(2, CardType.Skill, CardRarity.Rare, new DuchessEffect[] { new("ShuffleDiscardAll", 0m, 0m, ""), new("Draw", 3m, 4m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessMidnightWaltz"] = new(2, CardType.Attack, CardRarity.Rare, new DuchessEffect[] { new("Damage", 5m, 6m, ""), new("Draw", 2m, 3m, "moment") }, Hits: 4, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 6, RestageDivisor: 0),
["DuchessLastWord"] = new(3, CardType.Attack, CardRarity.Rare, new DuchessEffect[] { new("Damage", 32m, 40m, ""), new("Draw", 3m, 4m, "moment") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 7, RestageDivisor: 0),
["DuchessVanishingAct"] = new(2, CardType.Skill, CardRarity.Rare, new DuchessEffect[] { new("Block", 18m, 24m, ""), new("DodgeToHand", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessSilverStorm"] = new(2, CardType.Attack, CardRarity.Rare, new DuchessEffect[] { new("Damage", 5m, 7m, "") }, Hits: 3, All: true, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessBothPaths"] = new(2, CardType.Skill, CardRarity.Rare, new DuchessEffect[] { new("ShuffleHand", 2m, 3m, ""), new("AllyBlock", 8m, 11m, ""), new("Draw", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessDawnPromise"] = new(2, CardType.Power, CardRarity.Rare, new DuchessEffect[] { new("DodgeAtTurnStart", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessSteadyHand"] = new(1, CardType.Power, CardRarity.Rare, new DuchessEffect[] { new("Strength", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessLightAsSilk"] = new(1, CardType.Power, CardRarity.Rare, new DuchessEffect[] { new("Dexterity", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessBorrowedTime"] = new(0, CardType.Skill, CardRarity.Rare, new DuchessEffect[] { new("Energy", 2m, 3m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessThiefsArsenal"] = new(2, CardType.Skill, CardRarity.Rare, new DuchessEffect[] { new("DodgeToHand", 3m, 3m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: true, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessPerfectRehearsal"] = new(3, CardType.Skill, CardRarity.Rare, new DuchessEffect[] { new("RewindTurn", 0m, 0m, ""), new("SetMoment", 3m, 3m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessNightfall"] = new(2, CardType.Skill, CardRarity.Rare, new DuchessEffect[] { new("Weak", 3m, 4m, ""), new("Vulnerable", 2m, 3m, "") }, Hits: 1, All: true, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessSharedStage"] = new(2, CardType.Skill, CardRarity.Rare, new DuchessEffect[] { new("AllyBlock", 12m, 16m, ""), new("AllyDodge", 1m, 2m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessUnbrokenPoise"] = new(2, CardType.Power, CardRarity.Rare, new DuchessEffect[] { new("ShuffleBlock", 3m, 4m, "") }, Hits: 1, All: false, Exhaust: false, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessEternalRestage"] = new(0, CardType.Attack, CardRarity.Ancient, new DuchessEffect[] { new("Damage", 6m, 8m, "") }, Hits: 1, All: false, Exhaust: false, Retain: true, UpgradeTokens: false, Reaction: false, Moment: 5, RestageDivisor: 2),
["DuchessFirstLight"] = new(1, CardType.Skill, CardRarity.Ancient, new DuchessEffect[] { new("AllyDodge", 2m, 3m, ""), new("AllyBlock", 8m, 12m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: false, Moment: 0, RestageDivisor: 0),
["DuchessDodge"] = new(1, CardType.Skill, CardRarity.Token, new DuchessEffect[] { new("Block", 6m, 9m, ""), new("Draw", 1m, 1m, "") }, Hits: 1, All: false, Exhaust: true, Retain: false, UpgradeTokens: false, Reaction: true, Moment: 0, RestageDivisor: 0),
}; }
public sealed class DuchessStrike : DuchessCard { public DuchessStrike() : base(nameof(DuchessStrike)) { } }
public sealed class DuchessDefend : DuchessCard { public DuchessDefend() : base(nameof(DuchessDefend)) { } }
public sealed class DuchessRestage : DuchessCard { public DuchessRestage() : base(nameof(DuchessRestage)) { } }
public sealed class DuchessElegantBearing : DuchessCard { public DuchessElegantBearing() : base(nameof(DuchessElegantBearing)) { } }
public sealed class DuchessStiletto : DuchessCard { public DuchessStiletto() : base(nameof(DuchessStiletto)) { } }
public sealed class DuchessTwinFangs : DuchessCard { public DuchessTwinFangs() : base(nameof(DuchessTwinFangs)) { } }
public sealed class DuchessPassingCut : DuchessCard { public DuchessPassingCut() : base(nameof(DuchessPassingCut)) { } }
public sealed class DuchessLowSweep : DuchessCard { public DuchessLowSweep() : base(nameof(DuchessLowSweep)) { } }
public sealed class DuchessNeedlework : DuchessCard { public DuchessNeedlework() : base(nameof(DuchessNeedlework)) { } }
public sealed class DuchessOpeningThrust : DuchessCard { public DuchessOpeningThrust() : base(nameof(DuchessOpeningThrust)) { } }
public sealed class DuchessFollowThrough : DuchessCard { public DuchessFollowThrough() : base(nameof(DuchessFollowThrough)) { } }
public sealed class DuchessBlindSpot : DuchessCard { public DuchessBlindSpot() : base(nameof(DuchessBlindSpot)) { } }
public sealed class DuchessSerratedEdge : DuchessCard { public DuchessSerratedEdge() : base(nameof(DuchessSerratedEdge)) { } }
public sealed class DuchessGlintstoneKnife : DuchessCard { public DuchessGlintstoneKnife() : base(nameof(DuchessGlintstoneKnife)) { } }
public sealed class DuchessPartingCut : DuchessCard { public DuchessPartingCut() : base(nameof(DuchessPartingCut)) { } }
public sealed class DuchessMeasuredStep : DuchessCard { public DuchessMeasuredStep() : base(nameof(DuchessMeasuredStep)) { } }
public sealed class DuchessSilkenGuard : DuchessCard { public DuchessSilkenGuard() : base(nameof(DuchessSilkenGuard)) { } }
public sealed class DuchessPivot : DuchessCard { public DuchessPivot() : base(nameof(DuchessPivot)) { } }
public sealed class DuchessVeiledStep : DuchessCard { public DuchessVeiledStep() : base(nameof(DuchessVeiledStep)) { } }
public sealed class DuchessFeint : DuchessCard { public DuchessFeint() : base(nameof(DuchessFeint)) { } }
public sealed class DuchessReadTheRoom : DuchessCard { public DuchessReadTheRoom() : base(nameof(DuchessReadTheRoom)) { } }
public sealed class DuchessTakeABreath : DuchessCard { public DuchessTakeABreath() : base(nameof(DuchessTakeABreath)) { } }
public sealed class DuchessHiddenPocket : DuchessCard { public DuchessHiddenPocket() : base(nameof(DuchessHiddenPocket)) { } }
public sealed class DuchessSoftLanding : DuchessCard { public DuchessSoftLanding() : base(nameof(DuchessSoftLanding)) { } }
public sealed class DuchessReverberation : DuchessCard { public DuchessReverberation() : base(nameof(DuchessReverberation)) { } }
public sealed class DuchessPoised : DuchessCard { public DuchessPoised() : base(nameof(DuchessPoised)) { } }
public sealed class DuchessCurtainTug : DuchessCard { public DuchessCurtainTug() : base(nameof(DuchessCurtainTug)) { } }
public sealed class DuchessDistraction : DuchessCard { public DuchessDistraction() : base(nameof(DuchessDistraction)) { } }
public sealed class DuchessTripleWaltz : DuchessCard { public DuchessTripleWaltz() : base(nameof(DuchessTripleWaltz)) { } }
public sealed class DuchessDaggerFan : DuchessCard { public DuchessDaggerFan() : base(nameof(DuchessDaggerFan)) { } }
public sealed class DuchessPerfectAngle : DuchessCard { public DuchessPerfectAngle() : base(nameof(DuchessPerfectAngle)) { } }
public sealed class DuchessMaskedAssault : DuchessCard { public DuchessMaskedAssault() : base(nameof(DuchessMaskedAssault)) { } }
public sealed class DuchessDancePartner : DuchessCard { public DuchessDancePartner() : base(nameof(DuchessDancePartner)) { } }
public sealed class DuchessCutAndFade : DuchessCard { public DuchessCutAndFade() : base(nameof(DuchessCutAndFade)) { } }
public sealed class DuchessPaleMoonblade : DuchessCard { public DuchessPaleMoonblade() : base(nameof(DuchessPaleMoonblade)) { } }
public sealed class DuchessNoWitness : DuchessCard { public DuchessNoWitness() : base(nameof(DuchessNoWitness)) { } }
public sealed class DuchessSecondThought : DuchessCard { public DuchessSecondThought() : base(nameof(DuchessSecondThought)) { } }
public sealed class DuchessThreadTheGap : DuchessCard { public DuchessThreadTheGap() : base(nameof(DuchessThreadTheGap)) { } }
public sealed class DuchessSilverFlash : DuchessCard { public DuchessSilverFlash() : base(nameof(DuchessSilverFlash)) { } }
public sealed class DuchessUnderstudy : DuchessCard { public DuchessUnderstudy() : base(nameof(DuchessUnderstudy)) { } }
public sealed class DuchessEncore : DuchessCard { public DuchessEncore() : base(nameof(DuchessEncore)) { } }
public sealed class DuchessHeldBreath : DuchessCard { public DuchessHeldBreath() : base(nameof(DuchessHeldBreath)) { } }
public sealed class DuchessInvitation : DuchessCard { public DuchessInvitation() : base(nameof(DuchessInvitation)) { } }
public sealed class DuchessTurnAside : DuchessCard { public DuchessTurnAside() : base(nameof(DuchessTurnAside)) { } }
public sealed class DuchessBackstage : DuchessCard { public DuchessBackstage() : base(nameof(DuchessBackstage)) { } }
public sealed class DuchessQuietSignal : DuchessCard { public DuchessQuietSignal() : base(nameof(DuchessQuietSignal)) { } }
public sealed class DuchessMoonlitVeil : DuchessCard { public DuchessMoonlitVeil() : base(nameof(DuchessMoonlitVeil)) { } }
public sealed class DuchessDressRehearsal : DuchessCard { public DuchessDressRehearsal() : base(nameof(DuchessDressRehearsal)) { } }
public sealed class DuchessQuickHands : DuchessCard { public DuchessQuickHands() : base(nameof(DuchessQuickHands)) { } }
public sealed class DuchessStolenMoment : DuchessCard { public DuchessStolenMoment() : base(nameof(DuchessStolenMoment)) { } }
public sealed class DuchessSway : DuchessCard { public DuchessSway() : base(nameof(DuchessSway)) { } }
public sealed class DuchessElegance : DuchessCard { public DuchessElegance() : base(nameof(DuchessElegance)) { } }
public sealed class DuchessComposure : DuchessCard { public DuchessComposure() : base(nameof(DuchessComposure)) { } }
public sealed class DuchessAfterglow : DuchessCard { public DuchessAfterglow() : base(nameof(DuchessAfterglow)) { } }
public sealed class DuchessHiddenRhythm : DuchessCard { public DuchessHiddenRhythm() : base(nameof(DuchessHiddenRhythm)) { } }
public sealed class DuchessUnseenResolve : DuchessCard { public DuchessUnseenResolve() : base(nameof(DuchessUnseenResolve)) { } }
public sealed class DuchessFinale : DuchessCard { public DuchessFinale() : base(nameof(DuchessFinale)) { } }
public sealed class DuchessGrandReprise : DuchessCard { public DuchessGrandReprise() : base(nameof(DuchessGrandReprise)) { } }
public sealed class DuchessMidnightWaltz : DuchessCard { public DuchessMidnightWaltz() : base(nameof(DuchessMidnightWaltz)) { } }
public sealed class DuchessLastWord : DuchessCard { public DuchessLastWord() : base(nameof(DuchessLastWord)) { } }
public sealed class DuchessVanishingAct : DuchessCard { public DuchessVanishingAct() : base(nameof(DuchessVanishingAct)) { } }
public sealed class DuchessSilverStorm : DuchessCard { public DuchessSilverStorm() : base(nameof(DuchessSilverStorm)) { } }
public sealed class DuchessBothPaths : DuchessCard { public DuchessBothPaths() : base(nameof(DuchessBothPaths)) { } }
public sealed class DuchessDawnPromise : DuchessCard { public DuchessDawnPromise() : base(nameof(DuchessDawnPromise)) { } }
public sealed class DuchessSteadyHand : DuchessCard { public DuchessSteadyHand() : base(nameof(DuchessSteadyHand)) { } }
public sealed class DuchessLightAsSilk : DuchessCard { public DuchessLightAsSilk() : base(nameof(DuchessLightAsSilk)) { } }
public sealed class DuchessBorrowedTime : DuchessCard { public DuchessBorrowedTime() : base(nameof(DuchessBorrowedTime)) { } }
public sealed class DuchessThiefsArsenal : DuchessCard { public DuchessThiefsArsenal() : base(nameof(DuchessThiefsArsenal)) { } }
public sealed class DuchessPerfectRehearsal : DuchessCard { public DuchessPerfectRehearsal() : base(nameof(DuchessPerfectRehearsal)) { } }
public sealed class DuchessNightfall : DuchessCard { public DuchessNightfall() : base(nameof(DuchessNightfall)) { } }
public sealed class DuchessSharedStage : DuchessCard { public DuchessSharedStage() : base(nameof(DuchessSharedStage)) { } }
public sealed class DuchessUnbrokenPoise : DuchessCard { public DuchessUnbrokenPoise() : base(nameof(DuchessUnbrokenPoise)) { } }
public sealed class DuchessEternalRestage : DuchessCard { public DuchessEternalRestage() : base(nameof(DuchessEternalRestage)) { } }
public sealed class DuchessFirstLight : DuchessCard { public DuchessFirstLight() : base(nameof(DuchessFirstLight)) { } }
public sealed class DuchessDodge : DuchessCard { public DuchessDodge() : base(nameof(DuchessDodge)) { } }
