using Godot;
using MegaCrit.Sts2.Core.Models;
using NightMustStay.Core.Models.Cards;
namespace NightMustStay.Core.Models.CardPools;
public sealed class DuchessCardPool : CardPoolModel
{
    public override string Title => "duchess";
    public override string EnergyColorName => "duchess";
    public override string CardFrameMaterialPath => "card_frame_duchess";
    public override Color DeckEntryCardColor => new("809CC8");
    public override Color EnergyOutlineColor => new("17243D");
    public override bool IsColorless => false;
    protected override CardModel[] GenerateAllCards() => new CardModel[] {
        ModelDb.Card<DuchessStrike>(),
        ModelDb.Card<DuchessDefend>(),
        ModelDb.Card<DuchessRestage>(),
        ModelDb.Card<DuchessElegantBearing>(),
        ModelDb.Card<DuchessBladeRevealMoment>(),
        ModelDb.Card<DuchessCarianSlicer>(),
        ModelDb.Card<DuchessGreatswordPhalanx>(),
        ModelDb.Card<DuchessMiquellasHalo>(),
        ModelDb.Card<DuchessCarianSwordsmanship>(),
        ModelDb.Card<DuchessMagicDagger>(),
        ModelDb.Card<DuchessReturningCrosscut>(),
        ModelDb.Card<DuchessWaitAMoment>(),
        ModelDb.Card<DuchessOpeningMoment>(),
        ModelDb.Card<DuchessEphemeral>(),
        ModelDb.Card<DuchessOverdraw>(),
        ModelDb.Card<DuchessForeseeFuture>(),
        ModelDb.Card<DuchessBackToPast>(),
        ModelDb.Card<DuchessUndecidedFate>(),
        ModelDb.Card<DuchessReverseTime>(),
        ModelDb.Card<DuchessReveal>(),
        ModelDb.Card<DuchessPassingCut>(),
        ModelDb.Card<DuchessBlindSpot>(),
        ModelDb.Card<DuchessPoisedExit>(),
        ModelDb.Card<DuchessGlintstoneHail>(),
        ModelDb.Card<DuchessGlintstoneKnife>(),
        ModelDb.Card<DuchessPivot>(),
        ModelDb.Card<DuchessVeiledStep>(),
        ModelDb.Card<DuchessFeint>(),
        ModelDb.Card<DuchessSwayingStep>(),
        ModelDb.Card<DuchessRadiantBladeArray>(),
        ModelDb.Card<DuchessHiddenPocket>(),
        ModelDb.Card<DuchessSoftLanding>(),
        ModelDb.Card<DuchessReverberation>(),
        ModelDb.Card<DuchessDistraction>(),
        ModelDb.Card<DuchessThreadTheGap>(),
        ModelDb.Card<DuchessSilverFlash>(),
        ModelDb.Card<DuchessGapMoonshadow>(),
        ModelDb.Card<DuchessInvitation>(),
        ModelDb.Card<DuchessQuickHands>(),
        ModelDb.Card<DuchessComposure>(),
        ModelDb.Card<DuchessLightningNerves>(),
        ModelDb.Card<DuchessFinale>(),
        ModelDb.Card<DuchessGrandReprise>(),
        ModelDb.Card<DuchessMidnightWaltz>(),
        ModelDb.Card<DuchessSilverStorm>(),
        ModelDb.Card<DuchessMagicRadiantBlade>(),
        ModelDb.Card<DuchessCariaPhalanx>(),
        ModelDb.Card<DuchessAngelWings>(),
        ModelDb.Card<DuchessFallingMagic>(),
        ModelDb.Card<DuchessThiefsArsenal>(),
        ModelDb.Card<DuchessPerfectRehearsal>(),
        ModelDb.Card<DuchessEternalRestage>(),
        ModelDb.Card<DuchessReenactment>(),
        ModelDb.Card<DuchessSideSomersault>(),
        ModelDb.Card<DuchessInitiative>(),
        ModelDb.Card<DuchessGoldenBlade>(),
        ModelDb.Card<DuchessCarianGreatsword>(),
        ModelDb.Card<DuchessCarianPiercer>(),
        ModelDb.Card<DuchessRadiantBladeMagic>(),
        ModelDb.Card<DuchessDeathBlade>(),
        ModelDb.Card<DuchessCarianRetaliation>(),
        ModelDb.Card<DuchessCalmComposure>(),
        ModelDb.Card<DuchessTidyCollar>(),
        ModelDb.Card<DuchessBeat>(),
        ModelDb.Card<DuchessSilence>(),
        ModelDb.Card<DuchessDuchess>(),
        ModelDb.Card<DuchessGrandBearing>(),
        ModelDb.Card<DuchessGoldenMoment>(),
        ModelDb.Card<DuchessLorettaMastery>(),
        ModelDb.Card<DuchessLorettaGreatbow>(),
        ModelDb.Card<DuchessSleightOfHand>(),
        ModelDb.Card<DuchessBecomeInvisible>(),
    };
}
