using Godot;
using MegaCrit.Sts2.Core.Models;
using NightMustStay.Core.Models.Cards;
namespace NightMustStay.Core.Models.CardPools;
public sealed class DuchessCardPool : CardPoolModel
{
    public override string Title => "duchess";
    public override string EnergyColorName => "duchess";
    public override string CardFrameMaterialPath => "card_frame_duchess";
    public override Color DeckEntryCardColor => new("809CC8");
    public override Color EnergyOutlineColor => new("17243D");
    public override bool IsColorless => false;
    protected override CardModel[] GenerateAllCards() => new CardModel[] {
        ModelDb.Card<DuchessStrike>(),
        ModelDb.Card<DuchessDefend>(),
        ModelDb.Card<DuchessRestage>(),
        ModelDb.Card<DuchessElegantBearing>(),
        ModelDb.Card<DuchessCarianSlicer>(),
        ModelDb.Card<DuchessMagicDagger>(),
        ModelDb.Card<DuchessReturningCrosscut>(),
        ModelDb.Card<DuchessWaitAMoment>(),
        ModelDb.Card<DuchessOpeningMoment>(),
        ModelDb.Card<DuchessEphemeral>(),
        ModelDb.Card<DuchessOverdraw>(),
        ModelDb.Card<DuchessForeseeFuture>(),
        ModelDb.Card<DuchessBackToPast>(),
        ModelDb.Card<DuchessUndecidedFate>(),
        ModelDb.Card<DuchessReverseTime>(),
        ModelDb.Card<DuchessReveal>(),
        ModelDb.Card<DuchessStiletto>(),
        ModelDb.Card<DuchessTwinFangs>(),
        ModelDb.Card<DuchessPassingCut>(),
        ModelDb.Card<DuchessLowSweep>(),
        ModelDb.Card<DuchessNeedlework>(),
        ModelDb.Card<DuchessOpeningThrust>(),
        ModelDb.Card<DuchessFollowThrough>(),
        ModelDb.Card<DuchessBlindSpot>(),
        ModelDb.Card<DuchessSerratedEdge>(),
        ModelDb.Card<DuchessGlintstoneKnife>(),
        ModelDb.Card<DuchessPartingCut>(),
        ModelDb.Card<DuchessMeasuredStep>(),
        ModelDb.Card<DuchessSilkenGuard>(),
        ModelDb.Card<DuchessPivot>(),
        ModelDb.Card<DuchessVeiledStep>(),
        ModelDb.Card<DuchessFeint>(),
        ModelDb.Card<DuchessReadTheRoom>(),
        ModelDb.Card<DuchessTakeABreath>(),
        ModelDb.Card<DuchessHiddenPocket>(),
        ModelDb.Card<DuchessSoftLanding>(),
        ModelDb.Card<DuchessReverberation>(),
        ModelDb.Card<DuchessPoised>(),
        ModelDb.Card<DuchessCurtainTug>(),
        ModelDb.Card<DuchessDistraction>(),
        ModelDb.Card<DuchessTripleWaltz>(),
        ModelDb.Card<DuchessDaggerFan>(),
        ModelDb.Card<DuchessPerfectAngle>(),
        ModelDb.Card<DuchessMaskedAssault>(),
        ModelDb.Card<DuchessDancePartner>(),
        ModelDb.Card<DuchessCutAndFade>(),
        ModelDb.Card<DuchessPaleMoonblade>(),
        ModelDb.Card<DuchessNoWitness>(),
        ModelDb.Card<DuchessSecondThought>(),
        ModelDb.Card<DuchessThreadTheGap>(),
        ModelDb.Card<DuchessSilverFlash>(),
        ModelDb.Card<DuchessUnderstudy>(),
        ModelDb.Card<DuchessEncore>(),
        ModelDb.Card<DuchessHeldBreath>(),
        ModelDb.Card<DuchessInvitation>(),
        ModelDb.Card<DuchessTurnAside>(),
        ModelDb.Card<DuchessBackstage>(),
        ModelDb.Card<DuchessQuietSignal>(),
        ModelDb.Card<DuchessMoonlitVeil>(),
        ModelDb.Card<DuchessDressRehearsal>(),
        ModelDb.Card<DuchessQuickHands>(),
        ModelDb.Card<DuchessStolenMoment>(),
        ModelDb.Card<DuchessSway>(),
        ModelDb.Card<DuchessElegance>(),
        ModelDb.Card<DuchessComposure>(),
        ModelDb.Card<DuchessAfterglow>(),
        ModelDb.Card<DuchessHiddenRhythm>(),
        ModelDb.Card<DuchessUnseenResolve>(),
        ModelDb.Card<DuchessFinale>(),
        ModelDb.Card<DuchessGrandReprise>(),
        ModelDb.Card<DuchessMidnightWaltz>(),
        ModelDb.Card<DuchessLastWord>(),
        ModelDb.Card<DuchessVanishingAct>(),
        ModelDb.Card<DuchessSilverStorm>(),
        ModelDb.Card<DuchessBothPaths>(),
        ModelDb.Card<DuchessDawnPromise>(),
        ModelDb.Card<DuchessSteadyHand>(),
        ModelDb.Card<DuchessLightAsSilk>(),
        ModelDb.Card<DuchessBorrowedTime>(),
        ModelDb.Card<DuchessThiefsArsenal>(),
        ModelDb.Card<DuchessPerfectRehearsal>(),
        ModelDb.Card<DuchessNightfall>(),
        ModelDb.Card<DuchessSharedStage>(),
        ModelDb.Card<DuchessUnbrokenPoise>(),
        ModelDb.Card<DuchessEternalRestage>(),
        ModelDb.Card<DuchessFirstLight>(),
    };
}
