<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AssemblyName>NightMustStay</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="tools\**\*.cs" />
    <Compile Remove=".godot\**\*.cs" />
    <Compile Remove="build\**\*.cs" />
    <EmbeddedResource Include="config.json" LogicalName="NightMustStay.telemetry.config.json" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>sts2dll\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="GodotSharp">
      <HintPath>sts2dll\GodotSharp.dll</HintPath>
    </Reference>
    <Reference Include="sts2">
      <HintPath>sts2dll\sts2.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
