const fs = require("fs");

function update(path, entries) {
  const data = JSON.parse(fs.readFileSync(path, "utf8"));
  Object.assign(data, entries);
  fs.writeFileSync(path, `${JSON.stringify(data, null, 2)}\n`, "utf8");
}

update("sts2mod/localization/zhs/cards.json", {
  "FINGER_SNAP.description": "触发1次该敌人的[gold]中毒[/gold]。",
  "FINGER_SNAP.upgradeDescription": "触发1次所有敌人的[gold]中毒[/gold]。",
  "POISON_BURST.title": "凋零箭",
  "POISON_BURST.description": "[gold]毒爆[/gold]{PoisonBurst:diff()}。\n造成{Damage:diff()}点伤害。",
  "POISON_BURST.upgradeDescription": "[gold]毒爆[/gold]{PoisonBurst:diff()}。\n造成{Damage:diff()}点伤害。",
  "IRONEYE_HEADSHOT.description": "造成{Damage:diff()}点伤害。\n如果该伤害触发[gold]标记[/gold]，额外造成等量伤害。",
  "IRONEYE_HEADSHOT.upgradeDescription": "造成{Damage:diff()}点伤害。\n如果该伤害触发[gold]标记[/gold]，额外造成等量伤害。",
  "PIERCE_THE_WILLOW.description": "扩大{Range:diff()}点[gold]标记[/gold]的伤害触发范围。",
  "PIERCE_THE_WILLOW.upgradeDescription": "扩大{Range:diff()}点[gold]标记[/gold]的伤害触发范围。",

  "LIGHTNING_ARROWHEAD.title": "引雷箭头",
  "LIGHTNING_ARROWHEAD.description": "每次触发[gold]远射[/gold]时，对随机敌人造成{Damage:diff()}点伤害。",
  "LIGHTNING_ARROWHEAD.upgradeDescription": "每次触发[gold]远射[/gold]时，对随机敌人造成{Damage:diff()}点伤害。",
  "BOW_LIKE_FULL_MOON.title": "弓如满月",
  "BOW_LIKE_FULL_MOON.description": "[gold]距离[/gold]不再扣除你的[gold]力量[/gold]。",
  "BOW_LIKE_FULL_MOON.upgradeDescription": "[gold]距离[/gold]不再扣除你的[gold]力量[/gold]。",
  "BLADE_SHADOW_UNMATCHED.title": "刀影无双",
  "BLADE_SHADOW_UNMATCHED.description": "[gold]距离[/gold]为负数时，为你提供双倍[gold]力量[/gold]加成。",
  "BLADE_SHADOW_UNMATCHED.upgradeDescription": "[gold]距离[/gold]为负数时，为你提供双倍[gold]力量[/gold]加成。",
  "CIRCLING_MANEUVER.title": "周旋",
  "CIRCLING_MANEUVER.description": "[gold]距离[/gold]+{Distance:diff()}。\n获得{Block:diff()}点[gold]格挡[/gold]。\n给予{Mark:diff()}层[gold]标记[/gold]。",
  "CIRCLING_MANEUVER.upgradeDescription": "[gold]距离[/gold]+{Distance:diff()}。\n获得{Block:diff()}点[gold]格挡[/gold]。\n给予{Mark:diff()}层[gold]标记[/gold]。",
  "WAVERING_STEP.title": "摇摆不定",
  "WAVERING_STEP.description": "[gold]距离[/gold]-{Distance:diff()}。\n下个回合开始时，[gold]距离[/gold]+{Distance:diff()}。",
  "WAVERING_STEP.upgradeDescription": "[gold]距离[/gold]-{Distance:diff()}。\n下个回合开始时，[gold]距离[/gold]+{Distance:diff()}。",
  "KILLING_INTENT_GAZE.title": "杀意凝视",
  "KILLING_INTENT_GAZE.description": "给予所有敌人{Mark:diff()}层[gold]标记[/gold]和{Poison:diff()}层[gold]中毒[/gold]。",
  "KILLING_INTENT_GAZE.upgradeDescription": "给予所有敌人{Mark:diff()}层[gold]标记[/gold]和{Poison:diff()}层[gold]中毒[/gold]。",
  "RETURN_TO_ZERO.title": "回归",
  "RETURN_TO_ZERO.description": "[gold]距离[/gold]-{Distance:diff()}。\n移动后[gold]距离[/gold]刚好为0时，获得{Energy:energyIcons()}。",
  "RETURN_TO_ZERO.upgradeDescription": "[gold]距离[/gold]-{Distance:diff()}。\n移动后[gold]距离[/gold]刚好为0时，获得{Energy:energyIcons()}。",
  "RETREAT_STEP.title": "后撤步",
  "RETREAT_STEP.description": "[gold]距离[/gold]+{Distance:diff()}。\n获得{Block:diff()}点[gold]格挡[/gold]。",
  "RETREAT_STEP.upgradeDescription": "[gold]距离[/gold]+{Distance:diff()}。\n获得{Block:diff()}点[gold]格挡[/gold]。",
  "WITHERING_SLASH.title": "凋零斩",
  "WITHERING_SLASH.description": "[gold]距离[/gold]-{Distance:diff()}。\n[gold]毒爆[/gold]{PoisonBurst:diff()}。\n造成{Damage:diff()}点伤害。",
  "WITHERING_SLASH.upgradeDescription": "[gold]距离[/gold]-{Distance:diff()}。\n[gold]毒爆[/gold]{PoisonBurst:diff()}。\n造成{Damage:diff()}点伤害。",
  "POISON_MIST_ARROW_ARRAY.title": "毒雾箭阵",
  "POISON_MIST_ARROW_ARRAY.description": "对所有敌人造成{Damage:diff()}点伤害，给予等量于所造成伤害的[gold]中毒[/gold]。",
  "POISON_MIST_ARROW_ARRAY.upgradeDescription": "对所有敌人造成{Damage:diff()}点伤害，给予等量于所造成伤害的[gold]中毒[/gold]。",
  "BOW_COMBAT_ART.title": "弓斗术",
  "BOW_COMBAT_ART.description": "造成{Damage:diff()}点伤害。\n[gold]距离[/gold]为-2或以下时，给予{Mark:diff()}层[gold]标记[/gold]。",
  "BOW_COMBAT_ART.upgradeDescription": "造成{Damage:diff()}点伤害。\n[gold]距离[/gold]为-2或以下时，给予{Mark:diff()}层[gold]标记[/gold]。",
  "BLADE_GLIDE.title": "刀锋滑行",
  "BLADE_GLIDE.description": "将[gold]距离[/gold]变为0。每移动1点[gold]距离[/gold]，就对所有敌人造成{Damage:diff()}点伤害。",
  "BLADE_GLIDE.upgradeDescription": "将[gold]距离[/gold]变为0。每移动1点[gold]距离[/gold]，就对所有敌人造成{Damage:diff()}点伤害。",
  "STAR_PLUCKER.title": "摘星手",
  "STAR_PLUCKER.description": "抽{Cards:diff()}张牌。如果抽到的牌为攻击牌，本回合内将其耗能变为0。",
  "STAR_PLUCKER.upgradeDescription": "抽{Cards:diff()}张牌。如果抽到的牌为攻击牌，本回合内将其耗能变为0。",
  "SCOUTING.title": "侦察",
  "SCOUTING.description": "获得{Block:diff()}点[gold]格挡[/gold]。\n给予所有敌人{Mark:diff()}层[gold]标记[/gold]。",
  "SCOUTING.upgradeDescription": "获得{Block:diff()}点[gold]格挡[/gold]。\n给予所有敌人{Mark:diff()}层[gold]标记[/gold]。",
  "POISON_BLADE.title": "毒刃",
  "POISON_BLADE.description": "本回合打出的下张攻击牌对敌人造成伤害时，给予等量[gold]中毒[/gold]。",
  "POISON_BLADE.upgradeDescription": "本回合打出的下张攻击牌对敌人造成伤害时，给予等量[gold]中毒[/gold]。",
  "AIM.title": "瞄准",
  "AIM.description": "给予{Mark:diff()}层[gold]标记[/gold]。\n抽{Cards:diff()}张牌。",
  "AIM.upgradeDescription": "给予{Mark:diff()}层[gold]标记[/gold]。\n抽{Cards:diff()}张牌。"
});

update("sts2mod/localization/eng/cards.json", {
  "FINGER_SNAP.description": "Trigger the target's [gold]Poison[/gold] once.",
  "FINGER_SNAP.upgradeDescription": "Trigger all enemies' [gold]Poison[/gold] once.",
  "POISON_BURST.title": "Withering Arrow",
  "POISON_BURST.description": "[gold]Poison Burst[/gold] {PoisonBurst:diff()}.\nDeal {Damage:diff()} damage.",
  "POISON_BURST.upgradeDescription": "[gold]Poison Burst[/gold] {PoisonBurst:diff()}.\nDeal {Damage:diff()} damage.",
  "IRONEYE_HEADSHOT.description": "Deal {Damage:diff()} damage.\nIf this damage triggers [gold]Mark[/gold], deal that much additional damage.",
  "IRONEYE_HEADSHOT.upgradeDescription": "Deal {Damage:diff()} damage.\nIf this damage triggers [gold]Mark[/gold], deal that much additional damage.",
  "PIERCE_THE_WILLOW.description": "Expand [gold]Mark[/gold]'s damage trigger range by {Range:diff()}.",
  "PIERCE_THE_WILLOW.upgradeDescription": "Expand [gold]Mark[/gold]'s damage trigger range by {Range:diff()}.",

  "LIGHTNING_ARROWHEAD.title": "Lightning Arrowhead",
  "LIGHTNING_ARROWHEAD.description": "Whenever [gold]Long Shot[/gold] triggers, deal {Damage:diff()} damage to a random enemy.",
  "LIGHTNING_ARROWHEAD.upgradeDescription": "Whenever [gold]Long Shot[/gold] triggers, deal {Damage:diff()} damage to a random enemy.",
  "BOW_LIKE_FULL_MOON.title": "Bow Like the Full Moon",
  "BOW_LIKE_FULL_MOON.description": "[gold]Distance[/gold] no longer reduces your [gold]Strength[/gold].",
  "BOW_LIKE_FULL_MOON.upgradeDescription": "[gold]Distance[/gold] no longer reduces your [gold]Strength[/gold].",
  "BLADE_SHADOW_UNMATCHED.title": "Unmatched Blade Shadow",
  "BLADE_SHADOW_UNMATCHED.description": "While [gold]Distance[/gold] is negative, it grants twice as much [gold]Strength[/gold].",
  "BLADE_SHADOW_UNMATCHED.upgradeDescription": "While [gold]Distance[/gold] is negative, it grants twice as much [gold]Strength[/gold].",
  "CIRCLING_MANEUVER.title": "Circle",
  "CIRCLING_MANEUVER.description": "[gold]Distance[/gold] +{Distance:diff()}.\nGain {Block:diff()} [gold]Block[/gold].\nApply {Mark:diff()} [gold]Mark[/gold].",
  "CIRCLING_MANEUVER.upgradeDescription": "[gold]Distance[/gold] +{Distance:diff()}.\nGain {Block:diff()} [gold]Block[/gold].\nApply {Mark:diff()} [gold]Mark[/gold].",
  "WAVERING_STEP.title": "Wavering Step",
  "WAVERING_STEP.description": "[gold]Distance[/gold] -{Distance:diff()}.\nAt the start of next turn, [gold]Distance[/gold] +{Distance:diff()}.",
  "WAVERING_STEP.upgradeDescription": "[gold]Distance[/gold] -{Distance:diff()}.\nAt the start of next turn, [gold]Distance[/gold] +{Distance:diff()}.",
  "KILLING_INTENT_GAZE.title": "Killing Intent Gaze",
  "KILLING_INTENT_GAZE.description": "Apply {Mark:diff()} [gold]Mark[/gold] and {Poison:diff()} [gold]Poison[/gold] to ALL enemies.",
  "KILLING_INTENT_GAZE.upgradeDescription": "Apply {Mark:diff()} [gold]Mark[/gold] and {Poison:diff()} [gold]Poison[/gold] to ALL enemies.",
  "RETURN_TO_ZERO.title": "Return",
  "RETURN_TO_ZERO.description": "[gold]Distance[/gold] -{Distance:diff()}.\nIf [gold]Distance[/gold] is exactly 0 after moving, gain {Energy:energyIcons()}.",
  "RETURN_TO_ZERO.upgradeDescription": "[gold]Distance[/gold] -{Distance:diff()}.\nIf [gold]Distance[/gold] is exactly 0 after moving, gain {Energy:energyIcons()}.",
  "RETREAT_STEP.title": "Retreat Step",
  "RETREAT_STEP.description": "[gold]Distance[/gold] +{Distance:diff()}.\nGain {Block:diff()} [gold]Block[/gold].",
  "RETREAT_STEP.upgradeDescription": "[gold]Distance[/gold] +{Distance:diff()}.\nGain {Block:diff()} [gold]Block[/gold].",
  "WITHERING_SLASH.title": "Withering Slash",
  "WITHERING_SLASH.description": "[gold]Distance[/gold] -{Distance:diff()}.\n[gold]Poison Burst[/gold] {PoisonBurst:diff()}.\nDeal {Damage:diff()} damage.",
  "WITHERING_SLASH.upgradeDescription": "[gold]Distance[/gold] -{Distance:diff()}.\n[gold]Poison Burst[/gold] {PoisonBurst:diff()}.\nDeal {Damage:diff()} damage.",
  "POISON_MIST_ARROW_ARRAY.title": "Poison Mist Arrow Array",
  "POISON_MIST_ARROW_ARRAY.description": "Deal {Damage:diff()} damage to ALL enemies. Apply [gold]Poison[/gold] equal to the damage dealt.",
  "POISON_MIST_ARROW_ARRAY.upgradeDescription": "Deal {Damage:diff()} damage to ALL enemies. Apply [gold]Poison[/gold] equal to the damage dealt.",
  "BOW_COMBAT_ART.title": "Bow Combat Art",
  "BOW_COMBAT_ART.description": "Deal {Damage:diff()} damage.\nIf [gold]Distance[/gold] is -2 or less, apply {Mark:diff()} [gold]Mark[/gold].",
  "BOW_COMBAT_ART.upgradeDescription": "Deal {Damage:diff()} damage.\nIf [gold]Distance[/gold] is -2 or less, apply {Mark:diff()} [gold]Mark[/gold].",
  "BLADE_GLIDE.title": "Blade Glide",
  "BLADE_GLIDE.description": "Set [gold]Distance[/gold] to 0. For each [gold]Distance[/gold] moved, deal {Damage:diff()} damage to ALL enemies.",
  "BLADE_GLIDE.upgradeDescription": "Set [gold]Distance[/gold] to 0. For each [gold]Distance[/gold] moved, deal {Damage:diff()} damage to ALL enemies.",
  "STAR_PLUCKER.title": "Star Plucker",
  "STAR_PLUCKER.description": "Draw {Cards:diff()} card. If it is an Attack, it costs 0 this turn.",
  "STAR_PLUCKER.upgradeDescription": "Draw {Cards:diff()} cards. Attacks drawn this way cost 0 this turn.",
  "SCOUTING.title": "Scouting",
  "SCOUTING.description": "Gain {Block:diff()} [gold]Block[/gold].\nApply {Mark:diff()} [gold]Mark[/gold] to ALL enemies.",
  "SCOUTING.upgradeDescription": "Gain {Block:diff()} [gold]Block[/gold].\nApply {Mark:diff()} [gold]Mark[/gold] to ALL enemies.",
  "POISON_BLADE.title": "Poison Blade",
  "POISON_BLADE.description": "The next Attack played this turn applies [gold]Poison[/gold] equal to its unblocked damage.",
  "POISON_BLADE.upgradeDescription": "The next Attack played this turn applies [gold]Poison[/gold] equal to its unblocked damage.",
  "AIM.title": "Aim",
  "AIM.description": "Apply {Mark:diff()} [gold]Mark[/gold].\nDraw {Cards:diff()} card.",
  "AIM.upgradeDescription": "Apply {Mark:diff()} [gold]Mark[/gold].\nDraw {Cards:diff()} cards."
});

update("sts2mod/localization/zhs/powers.json", {
  "DISTANCE_POWER.description": "获得等同于[gold]距离[/gold]的[gold]敏捷[/gold]，失去等同于[gold]距离[/gold]的[gold]力量[/gold]。[gold]距离[/gold]的最大值为5，最小值为-5。",
  "LONG_SHOT_POWER.description": "[gold]距离[/gold]为2或以上时，耗能-1{energyPrefix:energyIcons(1)}。",
  "POISON_BURST_POWER.title": "毒爆",
  "POISON_BURST_POWER.description": "对拥有对应层数[gold]中毒[/gold]的敌人造成伤害翻倍。",
  "PIERCE_THE_WILLOW_POWER.description": "扩大{Amount}点[gold]标记[/gold]的伤害触发范围。",
  "LIGHTNING_ARROWHEAD_POWER.title": "引雷箭头",
  "LIGHTNING_ARROWHEAD_POWER.description": "每次触发[gold]远射[/gold]时，对随机敌人造成{Amount}点伤害。",
  "BOW_LIKE_FULL_MOON_POWER.title": "弓如满月",
  "BOW_LIKE_FULL_MOON_POWER.description": "[gold]距离[/gold]不再扣除你的[gold]力量[/gold]。",
  "BLADE_SHADOW_UNMATCHED_POWER.title": "刀影无双",
  "BLADE_SHADOW_UNMATCHED_POWER.description": "[gold]距离[/gold]为负数时，为你提供双倍[gold]力量[/gold]加成。",
  "NEXT_TURN_DISTANCE_POWER.title": "回正距离",
  "NEXT_TURN_DISTANCE_POWER.description": "下个回合开始时，[gold]距离[/gold]+{Amount}。",
  "POISON_BLADE_POWER.title": "毒刃",
  "POISON_BLADE_POWER.description": "本回合打出的下张攻击牌对敌人造成伤害时，给予等量[gold]中毒[/gold]。"
});

update("sts2mod/localization/eng/powers.json", {
  "DISTANCE_POWER.description": "Gain [gold]Dexterity[/gold] equal to [gold]Distance[/gold] and lose [gold]Strength[/gold] equal to [gold]Distance[/gold]. Maximum [gold]Distance[/gold] is 5 and minimum is -5.",
  "POISON_BURST_POWER.title": "Poison Burst",
  "POISON_BURST_POWER.description": "Deal double damage to enemies with the corresponding amount of [gold]Poison[/gold].",
  "PIERCE_THE_WILLOW_POWER.description": "Expand [gold]Mark[/gold]'s damage trigger range by {Amount}.",
  "LIGHTNING_ARROWHEAD_POWER.title": "Lightning Arrowhead",
  "LIGHTNING_ARROWHEAD_POWER.description": "Whenever [gold]Long Shot[/gold] triggers, deal {Amount} damage to a random enemy.",
  "BOW_LIKE_FULL_MOON_POWER.title": "Bow Like the Full Moon",
  "BOW_LIKE_FULL_MOON_POWER.description": "[gold]Distance[/gold] no longer reduces your [gold]Strength[/gold].",
  "BLADE_SHADOW_UNMATCHED_POWER.title": "Unmatched Blade Shadow",
  "BLADE_SHADOW_UNMATCHED_POWER.description": "While [gold]Distance[/gold] is negative, it grants twice as much [gold]Strength[/gold].",
  "NEXT_TURN_DISTANCE_POWER.title": "Return Distance",
  "NEXT_TURN_DISTANCE_POWER.description": "At the start of next turn, [gold]Distance[/gold] +{Amount}.",
  "POISON_BLADE_POWER.title": "Poison Blade",
  "POISON_BLADE_POWER.description": "The next Attack played this turn applies [gold]Poison[/gold] equal to its unblocked damage."
});
